//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMvisual
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumoAgua
    {
        public string idConsumoAgua { get; set; }
        public string cedulaCliente { get; set; }
        public string promedioConsumoAgua { get; set; }
        public string consumoAguaActual { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
